apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 8082
    targetPort: 8082
    name: restapi
  selector:
    app: client
    release: {{ .Release.Name }}
  type: ClusterIP
