apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
    release: {{ .Release.Name }}
spec:
  minReadySeconds: 0
  replicas: 1
  strategy:
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
    type: RollingUpdate
  selector:
    matchLabels:
      app: server
      release: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 2
      containers:
      - name: server
        image: matteverett/server:latest
        imagePullPolicy: Always
        ports:
        - name: restapi
          containerPort: 8081
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
