apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: restapi
  selector:
    app: server
    release: {{ .Release.Name }}
  type: ClusterIP
